added sync action
salesforce/refocus-bot-participants pull request #16
Opened 2021-01-19 12:08 UTC by BrandonMurnane

## Participants Bot Pull Request

#### Subject: Added sync action

#### Files Changed With Description of Changes:
Added sync action and required config

2021-02-02 17:27 UTC, kriscfoster approved these changes
Just had one comment but no reason to block the PR

2021-02-02 17:27 UTC, kriscfoster commented on web/state/RoleManager.js
> +const SYNC_BOT_ID = require('../config.js').SYNC_BOT_ID;
@BrandonMurnane just a minor thing but `const { SYNC_BOT_ID } = require('../config.js');` might look cleaner.

2021-02-03 09:56 UTC, bu3 requested changes

2021-02-03 09:56 UTC, bu3 commented on web/state/RoleManager.js
> +    if (SYNC_BOT_ID){
Do you mind extracting this to a dedicated function to make this function more readable?

2021-02-03 10:34 UTC, LongweiDeng approved these changes

2021-02-11 10:11 UTC, merged